# Copyright 2026 MyIME Project.
# All rights reserved.

"""Generates AzooKey conjugation metadata from Mozc and IPADIC rules."""

import argparse
import sys


def _read_rows(path, columns):
  rows = []
  with open(path, encoding="utf-8") as stream:
    for line in stream:
      line = line.rstrip("\r\n")
      if not line or line.startswith("#"):
        continue
      row = line.split("\t")
      if len(row) < columns:
        raise ValueError(f"{path}: malformed row: {line}")
      rows.append(row)
  return rows


def _read_features(path):
  features = []
  with open(path, encoding="utf-8") as stream:
    for line in stream:
      line = line.rstrip("\r\n")
      if not line or line.startswith("#"):
        continue
      _, feature = line.split(None, 1)
      features.append(feature)
  return features


def _quote(value):
  return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument("--user_pos", required=True)
  parser.add_argument("--cforms", required=True)
  parser.add_argument("--mozc_id", required=True)
  parser.add_argument("--ipadic_id", required=True)
  parser.add_argument("--output", required=True)
  args = parser.parse_args()

  cforms = {}
  # cforms.def rows: type, form, value suffix, key suffix, base suffix.
  for row in _read_rows(args.cforms, 4):
    ctype, form = row[0].replace("\u2212", "\uff0d"), row[1]
    cforms.setdefault(ctype, []).append(form)

  mozc_features = _read_features(args.mozc_id)
  ipadic_features = sorted(
      {",".join(feature.split(",")[:6])
       for feature in _read_features(args.ipadic_id)})

  conjugations = []
  for _, pos_type, ctype, mozc_feature, *_ in _read_rows(args.user_pos, 4):
    if ctype == "*":
      continue
    ctype = ctype.replace("\u2212", "\uff0d")
    forms = []
    for form in cforms[ctype]:
      # Keep exactly the rows kept by dictionary/gen_user_pos_data.py.  That
      # generator performs a prefix lookup after substituting <cform>.
      lookup = mozc_feature.replace("<cform>", form)
      matching_mozc_features = [
          feature for feature in mozc_features if feature.startswith(lookup)
      ]
      if not matching_mozc_features:
        print(
            f"warning: {pos_type}: Mozc has no POS ID for "
            f"({ctype}, {form}); omitting it may require the base-form "
            "fallback",
            file=sys.stderr,
        )
        continue
      if (lookup not in matching_mozc_features or
          len(matching_mozc_features) > 1):
        print(
            f"warning: {pos_type}: Mozc POS lookup for ({ctype}, {form}) "
            "uses a prefix match, equivalent to a min(cid)-style fallback",
            file=sys.stderr,
        )
      kind = "形容詞" if pos_type == "ADJECTIVE" else "動詞"
      feature = f"{kind},自立,*,*,{ctype},{form}"
      exists_in_ipadic = feature in ipadic_features
      if not exists_in_ipadic:
        print(
            f"warning: {pos_type}: IPADIC has no entry for "
            f"({ctype}, {form}); skipping it",
            file=sys.stderr,
        )
      forms.append((form, exists_in_ipadic))
    if not forms or forms[0][0] != "基本形":
      raise ValueError(f"{pos_type}: first serialized form must be 基本形")
    conjugations.append((pos_type, ctype, forms))

  lines = [
      "// Generated by converter/gen_azookey_cforms.py. Do not edit.",
      "#ifndef MOZC_CONVERTER_AZOOKEY_CFORMS_INC_",
      "#define MOZC_CONVERTER_AZOOKEY_CFORMS_INC_",
      "",
      "#include <cstddef>",
      '#include "absl/strings/string_view.h"',
      '#include "protocol/user_dictionary_storage.pb.h"',
      "",
      "namespace mozc::azookey_internal {",
      "struct ConjugationForm {",
      "  absl::string_view name;",
      "  bool exists_in_ipadic;",
      "};",
      "struct ConjugationData {",
      "  user_dictionary::UserDictionary::PosType pos_type;",
      "  absl::string_view conjugation_type;",
      "  const ConjugationForm* forms;",
      "  size_t form_count;",
      "};",
      "",
  ]
  for pos_type, _, forms in conjugations:
    lines.append(f"inline constexpr ConjugationForm k{pos_type}Forms[] = {{")
    for form, valid in forms:
      lines.append(f"    {{{_quote(form)}, {'true' if valid else 'false'}}},")
    lines.extend(["};", ""])
  lines.append("inline constexpr ConjugationData kConjugationData[] = {")
  for pos_type, ctype, forms in conjugations:
    lines.append(
        "    {user_dictionary::UserDictionary::" + pos_type + ", " +
        _quote(ctype) + f", k{pos_type}Forms, {len(forms)}}},")
  lines.extend([
      "};",
      "",
      "inline const ConjugationData* FindConjugationData(",
      "    user_dictionary::UserDictionary::PosType pos_type) {",
      "  for (const ConjugationData& data : kConjugationData) {",
      "    if (data.pos_type == pos_type) return &data;",
      "  }",
      "  return nullptr;",
      "}",
      "",
      "inline constexpr absl::string_view kIpadicFeatures[] = {",
  ])
  lines.extend(f"    {_quote(feature)}," for feature in ipadic_features)
  lines.extend([
      "};",
      "",
      "inline bool IsIpadicFeature(absl::string_view feature) {",
      "  for (absl::string_view candidate : kIpadicFeatures) {",
      "    if (candidate == feature) return true;",
      "  }",
      "  return false;",
      "}",
      "}  // namespace mozc::azookey_internal",
      "",
      "#endif  // MOZC_CONVERTER_AZOOKEY_CFORMS_INC_",
      "",
  ])
  with open(args.output, "w", encoding="utf-8", newline="\n") as stream:
    stream.write("\n".join(lines))


if __name__ == "__main__":
  main()
